config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Resource routes
  resources :artworks
  resources :book_chapters
  resources :books
  resources :colleges
  resources :digital_projects
  resources :editings
  resources :films
  resources :journal_articles
  resources :musical_scores
  resources :other_publications
  resources :photographies
  resources :physical_media
  resources :plays
  resources :public_performances
  resources :submitters

  # Admin-related routes
  get 'citations', to: 'admin#citations'
  get 'toggle_links', to: 'admin#toggle_links'
  get 'manage', to: 'admin#login'
  post 'manage/validate', to: 'admin#validate'
  get '/csv/:controller_name', to: 'admin#csv', as: 'controller_name'

  # Publications and submission routes
  get 'publications', to: 'publications#index'
  get 'publications/:id', to: 'publications#index'
  get 'finished', to: 'submitters#finished'

  # Dynamic pages
  get '/pages/:page' => 'pages#show'

  # Root URL
  root 'submitters#new'

  # Custom Error Pages
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#not_found', via: :all
end

app/models/other_publication.rb
# frozen_string_literal: true

class OtherPublication < ApplicationRecord
  include Csv
  has_and_belongs_to_many :colleges
  validates :work_title, presence: true
  validate :validate_author_names
  serialize :author_first_name, Array
  serialize :author_last_name, Array

  def self.to_csv
    attributes = %w[submitter_id work_title other_title authors colleges uc_department volume issue page_numbers publisher city publication_date url doi]
    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |item|
        csv << attributes.map { |attr| item.send(attr) }
      end
    end
  end
end

app/controllers/other_publications_controller.rb
# frozen_string_literal: true

class OtherPublicationsController < PublicationsController
  include UserAuthentication
  include CacheHeaderControl

  # Never trust parameters from the scary internet, only allow the white list through.
  def allowed_params
    params.require(:other_publication).permit(:uc_department, :work_title, :other_title, :volume, :issue, :page_numbers, :publisher, :city, :publication_date, :url, :doi, :other_college, :submitter_id, author_first_name: [], author_last_name: [], college_ids: [])
  end
  helper_method :allowed_params
end

app/helpers/other_publications_helper.rb
# frozen_string_literal: true

module OtherPublicationsHelper
  def find_other_publications(id)
    Array.wrap(OtherPublication.where(submitter_id: id))
  end
end

app/views/other_publications/_form.html.erb
<%= form_with(model: other_publication, local: true) do |form| %>
  <% if other_publication.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading"><%= pluralize(other_publication.errors.count, "error") %> found:</h4>
      <hr>
      <% other_publication.errors.full_messages.each do |message| %>
      <p class="mb-0"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%= render partial: "partials/author", locals: {name: "other_publication", publication: @other_publication} %>
  <hr>

  <%= render partial: "partials/publications_colleges", locals: {form: form} %>
  <hr>


  <div class="form-row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label(:uc_department, "UC Department(s) or Division(s)") %>
        <%= form.text_field :uc_department, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :work_title, 'Title of Submitted Work', class: "required" %>
        <%= form.text_field :work_title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :other_title, 'Other Title' %>
        <%= form.text_field :other_title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :volume %>
        <%= form.text_field :volume, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= form.label :issue %>
        <%= form.text_field :issue, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :page_numbers, 'Page Numbers' %>
      <%= form.text_field :page_numbers, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :publisher %>
      <%= form.text_field :publisher, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :publication_date, 'Publisher Date' %>
      <%= form.text_field :publication_date, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :city %>
      <%= form.text_field :city, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= form.label :url, 'URL (if this publication is available online)' %>
      <%= form.text_field :url, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <%= form.label :doi, 'DOI (Digital Object Identifier)' %>
      <%= form.text_field :doi, class: "form-control" %>
    </div>
  </div>

  <%= hidden_field_tag "other_publication[submitter_id]", session[:submitter_id] || @other_publication.submitter_id %>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/other_publications/_index.html.erb
<div class="row mt-4">
  <h1 class="pl-2">Other Publications<%= if session[:admin] then " (#{@other_publication_count})" end %></h1>
  <% if @other_publications.count < 3 && session[:admin] != true %>
    <div class="my-auto pl-3">
        <%= link_to 'New', new_other_publication_path, class: "btn btn-primary" %>
    </div>
  <% elsif params[:id].nil? && session[:admin]  %>
    <div class="my-auto pl-3">
      <%= link_to '<i class="fas fa-file-download icon-blue" data-toggle="tooltip" data-placement="top" title="Download CSV"></i>'.html_safe, csv_route("other_publications") %>
    </div>
    <div class=" ml-auto my-auto pl-3">
      <%= pagy_bootstrap_nav(@pagy_other_publications).html_safe %>
    </div>
  <% end %>
</div>

<% if @other_publications.count != 0 %>
<div class="row table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
      <th>Title of Submitted Work</th>
      <th>Author(s)</th>
      <th>Author College(s)</th>
      <th>UC Department(s) or Division(s)</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @other_publications.each do |other_publication| %>
      <tr>
        <td><%= link_to shorten_long(other_publication.work_title), other_publication %></td>
        <td>
        <% authors_array(other_publication).each do |item| %>
        <div><%= item %></div>
        <% end %>
        </td>
        <td>
        <% college_array(other_publication).each do |item| %>
        <div><%= item %></div>
        <% end %>
        </td>
        <td><%= shorten_long(other_publication.uc_department) %></td>
        <td><%= link_to '<i class="fas fa-edit icon-black" data-toggle="tooltip" data-placement="top" title="Edit"></i>'.html_safe, edit_other_publication_path(other_publication) %></td>
        <td><%= link_to '<i class="fas fa-trash icon-red" data-toggle="tooltip" data-placement="top" title="Delete"></i>'.html_safe, other_publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<% end %>

app/views/other_publications/edit.html.erb
<div class="container offset-footer">

    <div class="row pl-2">
        <h1>Editing Other Publication</h1>
    </div>

    <%= render 'form', other_publication: @other_publication %>

</div>

app/views/other_publications/new.html.erb
<div class="container offset-footer">

    <div class="row pl-2">
        <h1>New Other Publication</h1>
    </div>

    <%= render 'form', other_publication: @other_publication %>

</div>

app/views/other_publications/show.html.erb
<div class="container offset-footer">
  <div class="row pl-2">
    <h1>Show Other Publication</h1>
  </div>

  <div class="row pl-2">
    <p>Your publication's details are displayed below. Click <%= link_to "here", publications_path %> to return to your list of publications.</p>
  </div>

  <div class="row table-responsive">
    <table class="table table-hover">
      <tbody>
        <tr>
          <th scope="row">Author(s):</th>
          <td><%= all_authors(@other_publication) %></td>
        </tr>

        <tr>
          <th scope="row">Author College(s):</th>
          <td>
            <%= all_colleges(@other_publication.college_ids) + check_other_college(@other_publication) %>
          </td>
        </tr>

        <tr>
          <th scope="row">UC Department(s) or Division(s):</th>
          <td><%= @other_publication.uc_department %></td>
        </tr>

        <tr>
          <th scope="row">Title of Submitted Work:</th>
          <td><%= @other_publication.work_title %></td>
        </tr>

        <tr>
          <th scope="row">Other Title:</th>
          <td><%= @other_publication.other_title %></td>
        </tr>

        <tr>
          <th scope="row">Volume:</th>
          <td><%= @other_publication.volume %></td>
        </tr>

        <tr>
          <th scope="row">Issue:</th>
          <td><%= @other_publication.issue %></td>
        </tr>

        <tr>
          <th scope="row">Page Numbers:</th>
          <td><%= @other_publication.page_numbers %></td>
        </tr>

        <tr>
          <th scope="row">Publisher:</th>
          <td><%= @other_publication.publisher %></td>
        </tr>

        <tr>
          <th scope="row">City:</th>
          <td><%= @other_publication.city %></td>
        </tr>

        <tr>
          <th scope="row">Publication Date:</th>
          <td><%= @other_publication.publication_date %></td>
        </tr>

        <tr>
          <th scope="row">URL (if this publication is available online):</th>
          <td><%= @other_publication.url %></td>
        </tr>

        <tr>
          <th scope="row">DOI (Digital Object Identifier):</th>
          <td><%= @other_publication.doi %></td>
        </tr>

        <% if session[:admin] %>
        
          <tr>
            <th scope="row">Submitter ID:</th>
            <td><%= link_to link_to @submitter.id.to_s, publications_id(@submitter.id) %></td>
          </tr>
          <tr>
            <th scope="row">Submitter Name:</th>
            <td><%= submitter_name(@submitter) %></td>
          </tr>

        <% end %>
      </tbody>
    </table>
  </div>
    
  <div class="row">
    <%= link_to 'Edit', edit_other_publication_path(@other_publication), class: "btn btn-primary" %>
  </div>
</div>